package comp132.examples.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Create a window and add a few components to it. This example illustrates how
 * a GUI is typically created by making a sub-class of JFrame, adding a
 * container to it and adding the components that make up the GUI to that
 * container. It makes no attempt to layout the components or respond to events
 * generated by the components. Other examples will illustrate typical
 * techniques for those tasks.
 * 
 * @author Grant Braught
 * @author Dickinson College
 * @version Sep 22, 2009
 */
public class MyFirstJavaGUI extends JFrame {

    public MyFirstJavaGUI() {
        /*
         * Invoke the JFrame constructor that sets the text that appears in
         * title bar of the JFrame's window.
         */
        super("My First Java GUI");

        /*
         * Configure the JFrame so that the program exits when the frame is
         * closed. By default the frame is just hidden but the program continues
         * to run.
         */
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        /*
         * Create a container to hold all of the components and add that
         * container to the JFrame. All of the components for our GUI will be
         * added to this container.
         */
        Container mainPanel = new JPanel();
        this.add(mainPanel);

        /*
         * Create a JButton set it's foreground color to blue and add it to the
         * container that we added to the JFrame.
         */
        JButton b1 = new JButton("Click Me!");
        b1.setForeground(Color.blue);
        mainPanel.add(b1);

        /*
         * Create a JSlider with the range 1700 to 1900, initial value of 1800,
         * major tick marks at 50's and minor tick marks at 10's with labels
         * displayed on the major tick marks and add it to the container that we
         * added to the JFrame.
         */
        JSlider s1 = new JSlider(1700, 1900);
        s1.setMajorTickSpacing(50);
        s1.setMinorTickSpacing(10);
        s1.setPaintTicks(true);
        s1.setPaintLabels(true);
        mainPanel.add(s1);

        /*
         * Calling pack() causes all of the components to be arranged within the
         * JFrame and the JFrame to be sized so that it will display all of the
         * components.
         */
        this.pack();
    }

    /**
     * Create an instance of MyFirstJavaGUI and display it on the screen.
     * 
     * @param args none
     */
    public static void main(String[] args) {
        MyFirstJavaGUI mfjGUI = new MyFirstJavaGUI();

        /*
         * MyFirstJavaGUI extends JFrame so it inherits all of the methods
         * defined by JFrame, one of which is setVisible. Invoking setVisible
         * with true causes the JFrame to be displayed on the screen.
         */
        mfjGUI.setVisible(true);
    }
}
